#ifndef __FASTIVA_STRING_POOL_H__
#define __FASTIVA_STRING_POOL_H__

&& OBSOLETE &&

#define FASTIVA_STRING_POOL		FASTIVA_MODULE_NAME(stringPool)
#define FASTIVA_EXTERNAL_STRING_INDEX_START  0x10000000

#if (FASTIVA_BUILD_TARGET == FASTIVA_BUILD_TARGET_EXTERNAL_COMPONENT) 
	#define FASTIVA_STRING_INDEX_START	FASTIVA_EXTERNAL_STRING_INDEX_START
#else
	#define FASTIVA_STRING_INDEX_START	0
#endif

#ifdef FASTIVA_PRELOAD_STRING_CONSTANTS
	#define PSTR$(idx, str)	FASTIVA_STRING_POOL[idx]
#else
	#define PSTR$(idx, str)	fastiva.getImmortalString(idx + FASTIVA_STRING_INDEX_START)
#endif

extern java_lang_String_p FASTIVA_STRING_POOL[];

#endif // __FASTIVA_STRING_POOL_H__
