#ifdef FASTIVA_END_OF_PREPROCESS
	FASTIVA_END_OF_PREPROCESS
#endif

#undef __FASTIVA_PREPROCESS_SUPER__

#undef JPP_CLASS
#undef FASTIVA_PREPROCESS_CLASS
#undef FASTIVA_IS_IN_PREPROCESS_LIBCORE_CLASS

#undef FASTIVA_FIELD
#undef FASTIVA_FIELD_CONSTANT
#undef FASTIVA_FIELD_STATIC

#undef FASTIVA_METHOD_VIRTUAL
#undef FASTIVA_METHOD_ABSTRACT
#undef FASTIVA_METHOD_OVERRIDE
#undef FASTIVA_METHOD_INTERFACE
#undef FASTIVA_METHOD_FINAL
#undef FASTIVA_METHOD_STATIC
#undef FASTIVA_METHOD_OVERRIDE_IFC
#undef FASTIVA_METHOD_OVERRIDE_ACC
#undef FASTIVA_METHOD_CONSTRUCTOR


#undef JPP_PREPROCESS_INHERITED_INTERFACES
#undef JPP_INHERITS_INTERFACE
#undef JPP_INHERITS_EMPTY_INTERFACE
#undef JPP_INHERITS_BYTECODE_INTERFACE
#undef JPP_PREPROCESS_SYSTEM_METHOD
#undef JPP_PREPROCESS_INSTANCE_DATA
#undef JPP_PREPROCESS_STATIC_DATA
#undef JPP_PREPROCESS_INSTANCE_METHOD
#undef JPP_PREPROCESS_STATIC_METHOD

#undef FASTIVA_END_OF_PREPROCESS

#include <fastiva/preprocess/prolog.h>

