ren dalvik_bytecode_OpcodeInfo.cpp                       vm__dalvik_bytecode_OpcodeInfo.cpp                    
ren dalvik_system_DexFile.cpp                            vm__dalvik_system_DexFile.cpp                         
ren dalvik_system_VMDebug.cpp                            vm__dalvik_system_VMDebug.cpp                         
ren dalvik_system_VMRuntime.cpp                          vm__dalvik_system_VMRuntime.cpp                       
ren dalvik_system_VMStack.cpp                            vm__dalvik_system_VMStack.cpp                         
ren dalvik_system_Zygote.cpp                             vm__dalvik_system_Zygote.cpp                          
ren java_lang_Class.cpp                                  vm__java_lang_Class.cpp                               
ren java_lang_Double.cpp                                 vm__java_lang_Double.cpp                              
ren java_lang_Float.cpp                                  vm__java_lang_Float.cpp                               
ren java_lang_Math.cpp                                   vm__java_lang_Math.cpp                                
ren java_lang_Object.cpp                                 vm__java_lang_Object.cpp                              
ren java_lang_Runtime.cpp                                vm__java_lang_Runtime.cpp                             
ren java_lang_String.cpp                                 vm__java_lang_String.cpp                              
ren java_lang_System.cpp                                 vm__java_lang_System.cpp                              
ren java_lang_Throwable.cpp                              vm__java_lang_Throwable.cpp                           
ren java_lang_VMClassLoader.cpp                          vm__java_lang_VMClassLoader.cpp                       
ren java_lang_VMThread.cpp                               vm__java_lang_VMThread.cpp                            
ren java_lang_reflect_AccessibleObject.cpp               vm__java_lang_reflect_AccessibleObject.cpp            
ren java_lang_reflect_Array.cpp                          vm__java_lang_reflect_Array.cpp                       
ren java_lang_reflect_Constructor.cpp                    vm__java_lang_reflect_Constructor.cpp                 
ren java_lang_reflect_Field.cpp                          vm__java_lang_reflect_Field.cpp                       
ren java_lang_reflect_Method.cpp                         vm__java_lang_reflect_Method.cpp                      
ren java_lang_reflect_Proxy.cpp                          vm__java_lang_reflect_Proxy.cpp                       
ren java_util_concurrent_atomic_AtomicLong.cpp           vm__java_util_concurrent_atomic_AtomicLong.cpp        
ren org_apache_harmony_dalvik_NativeTestTarget.cpp       vm__org_apache_harmony_dalvik_NativeTestTarget.cpp    
ren org_apache_harmony_dalvik_ddmc_DdmServer.cpp         vm__org_apache_harmony_dalvik_ddmc_DdmServer.cpp      
ren org_apache_harmony_dalvik_ddmc_DdmVmInternal.cpp     vm__org_apache_harmony_dalvik_ddmc_DdmVmInternal.cpp  
ren sun_misc_Unsafe.cpp                                  vm__sun_misc_Unsafe.cpp                               
